spring.application.name=journalApp

spring.data.mongodb.uri=${Mongo_URI}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

spring.data.mongodb.auto-index-creation=true

#logging.level.root=WARN
#logging.level.root=OFF
