spring.application.name=journalApp

# JWT CONFIGURATION :-
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# MONGO-DB CONFIGURATION :-
spring.data.mongodb.uri=${Mongo_URI}
spring.data.mongodb.auto-index-creation=true

# EMAIL SENDER CONFIGURATION :-
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_ID}
spring.mail.password=${APP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


#logging.level.root=WARN
#logging.level.root=OFF
